"use client";

import { Check, FileText, ShieldCheck, TriangleAlert, Upload, Waypoints } from "lucide-react";
import { application, financialSignals, policyRules, reportSections, verificationChecks } from "@/content/demo-data";
import { ProductShell, Metric } from "@/components/product/product-shell";
import { Status } from "@/components/ui/primitives";

export function DocumentFlow() { return <ProductShell title="Secure intake" status="Demonstration data"><div className="intake-scene"><div className="intake-doc"><FileText aria-hidden="true" /><strong>Bank_Statement_May.pdf</strong><span>12 pages / received</span><Status tone="green">Document ready</Status></div><div className="intake-flow"><i /><i /><i /></div><div className="intake-target"><Upload aria-hidden="true" /><strong>Secure application intake</strong><span>Files, business details, consented evidence</span></div></div></ProductShell>; }
export function HeroScene() { const stages = ["Documents received", "Data extraction", "Financial signals", "Policy evaluated", "Recommendation ready"]; return <ProductShell title="Underwriting decision context" status="Demonstration data" tone="green" stage="Explainable recommendation"><div className="hero-scene__stages" aria-label="Document-to-recommendation product states">{stages.map((stage, index) => <span key={stage}><b>{String(index + 1).padStart(2, "0")}</b>{stage}</span>)}</div><div className="hero-scene"><aside className="hero-scene__sidebar"><span>Application</span><strong>{application.business}</strong><p>{application.requested} requested</p><div className="document-stack"><div><FileText aria-hidden="true" /><span>May bank statement</span><Status tone="green">Parsed</Status></div><div><FileText aria-hidden="true" /><span>Application packet</span><Status tone="green">Received</Status></div><div><FileText aria-hidden="true" /><span>Business record</span><Status tone="blue">Verified</Status></div></div></aside><div className="hero-scene__analysis"><div className="scene-label"><span>Financial evidence</span><Status tone="blue">Signals generated</Status></div><div className="hero-chart"><svg viewBox="0 0 600 190" role="img" aria-label="Demonstration chart of stable revenue and deposit activity"><path d="M0 144 C52 120,78 136,121 109 S202 121,250 86 S330 100,374 60 S454 81,500 43 S560 58,600 28" fill="none" stroke="currentColor" strokeWidth="5" /><path d="M0 170H600M0 112H600M0 54H600" stroke="currentColor" strokeOpacity=".13" strokeDasharray="6 8" /></svg></div><div className="hero-signal-row"><Metric label="Average daily balance" value="$41.8k" note="Healthy" tone="green" /><Metric label="Existing positions" value="2" note="Review context" tone="amber" /><Metric label="NSF events" value="2" note="Within policy" tone="green" /></div></div><aside className="hero-scene__decision"><span>Policy evaluation</span><strong>Conditional approval</strong><p>Recommendation ready for funder review.</p><div><Status tone="green">3 rules passed</Status><Status tone="amber">1 exception</Status></div><dl><div><dt>Rationale</dt><dd>Stable revenue, verified business identity, existing positions require review.</dd></div><div><dt>Final control</dt><dd>Funder decision required</dd></div></dl></aside></div></ProductShell>; }
export function WorkflowScene() { const steps = ["Secure intake", "Document processing", "Financial analysis", "Verification", "Policy evaluation", "Recommendation"]; return <ProductShell title="Document to decision" status="Connected journey" stage="Evidence handoff"><div className="workflow-scene">{steps.map((step, index) => <div className={index === 2 ? "workflow-step is-current" : "workflow-step"} key={step}><b>{String(index + 1).padStart(2, "0")}</b><span>{step}</span></div>)}</div></ProductShell>; }
export function WorkspaceScene() { return <ProductShell title="Underwriting workspace" status="Demonstration data" tabs={["Summary", "Documents", "Bank analysis", "KYB/KYC", "Policy", "Decision memo"]}><div className="workspace-scene"><aside><strong>{application.business}</strong><span>Application context</span><dl><div><dt>Requested</dt><dd>{application.requested}</dd></div><div><dt>Owner</dt><dd>{application.owner}</dd></div></dl></aside><div className="workspace-main"><div className="workspace-score"><span>Decision context</span><strong>Conditional approval</strong><p>One policy exception requires review before a final funding decision.</p></div><div className="workspace-evidence"><span>Evidence connected</span><div><FileText aria-hidden="true" /><ShieldCheck aria-hidden="true" /><Waypoints aria-hidden="true" /></div></div></div></div></ProductShell>; }
export function FinancialScene() { return <ProductShell title="Financial signals" status="Demonstration data" tabs={["Revenue", "Deposits", "Balances", "Obligations"]}><div className="financial-scene"><div className="chart-area"><div className="chart-label"><span>Revenue consistency</span><strong>$284k avg. monthly revenue</strong></div><svg viewBox="0 0 520 170" role="img" aria-label="Static demonstration line chart showing stable monthly revenue"><path d="M0 128 C45 115,72 94,112 101 S177 77,220 89 S284 55,330 74 S402 50,440 64 S486 34,520 45" fill="none" stroke="currentColor" strokeWidth="4" /><path d="M0 158H520M0 108H520M0 58H520" stroke="currentColor" strokeOpacity=".14" strokeDasharray="5 8" /></svg></div><div className="signal-metrics">{financialSignals.map(([label, value, note, tone]) => <Metric key={label} label={label} value={value} note={note} tone={tone} />)}</div></div></ProductShell>; }
export function PolicyScene() { return <ProductShell title="Policy intelligence" status="Organisation policy / demo" tone="green"><div className="policy-scene"><div className="policy-head"><div><span>Application policy fit</span><strong>3 passed / 1 exception</strong></div><Status tone="amber">Manual review required</Status></div><div className="rule-table">{policyRules.map(([rule, criteria, observed, outcome]) => <div key={rule}><span>{rule}</span><span>{criteria}</span><strong>{observed}</strong><Status tone={outcome === "Pass" ? "green" : "amber"}>{outcome}</Status></div>)}</div></div></ProductShell>; }
export function VerificationScene() { return <ProductShell title="Verification and fraud investigation" status="Demonstration data"><div className="verification-scene verification-scene--expanded"><div className="verification-list">{verificationChecks.map(([label, value, tone]) => <div key={label}><Check aria-hidden="true" /><span>{label}</span><Status tone={tone}>{value}</Status></div>)}</div><div className="entity-evidence"><div className="entity-evidence__map"><span>Business</span><i /><span>Address</span><i /><span>Owner</span><i /><span>Statement</span></div><div className="evidence-ledger"><div><span>Evidence link</span><strong>Registered address matches application</strong></div><div><span>Discrepancy</span><strong>Deposit concentration changed in final period</strong></div><div><span>Analyst context</span><strong>Review source transactions before final decision</strong></div></div></div><div className="fraud-evidence"><TriangleAlert aria-hidden="true" /><span>Manual review queue</span><strong>One linked signal requires resolution.</strong><p>Observed evidence is not an autonomous fraud conclusion and remains available for analyst inspection.</p></div></div></ProductShell>; }
export function DecisionScene() { return <ProductShell title="Explainable decision report" status="Demonstration data" tone="green"><div className="decision-scene"><div className="decision-summary"><span>Recommendation</span><strong>Conditional approval</strong><p>Score 82/100</p><Status tone="amber">Review existing positions</Status></div><ol>{reportSections.map((section, index) => <li key={section}><b>{String(index + 1).padStart(2, "0")}</b><span>{section}</span><Check aria-hidden="true" /></li>)}</ol></div></ProductShell>; }
export function SalesPricingScene() { return <ProductShell title="Funder Sales and Pricing" status="Decision support, not binding terms"><div className="sales-pricing"><div><span>Funder Sales</span><strong>Prioritise the opportunity</strong><p>Policy-fit context, missing information, and exception routing before underwriting handoff.</p><Status tone="green">Qualified for review</Status></div><div><span>Funder Pricing</span><strong>Ground recommendations in evidence</strong><p>Financial signals, repayment capacity, policy criteria, and human review in one decision context.</p><Status tone="blue">Terms require human approval</Status></div></div></ProductShell>; }
export function IntegrationScene() { const nodes = ["Embedded intake", "Documents", "Cevrynt intelligence", "LOS or CRM", "Decision report"]; return <ProductShell title="Workflow connection" status="Illustrative workflow"><div className="integration-scene">{nodes.map((node, index) => <div key={node}><span>{String(index + 1).padStart(2, "0")}</span><strong>{node}</strong></div>)}</div></ProductShell>; }
